name: flutter_trip
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # banner
  flutter_swiper: ^1.1.4
  # http
  http: ^0.12.0+1
  # webview
  flutter_webview_plugin: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/type_channelgroup.png
    - images/type_channelgs.png
    - images/type_channelplane.png
    - images/type_channeltrain.png
    - images/type_cruise.png
    - images/type_district.png
    - images/type_food.png
    - images/type_hotel.png
    - images/type_huodong.png
    - images/type_shop.png
    - images/type_sight.png
    - images/type_ticket.png
    - images/type_travelgroup.png
